### ISSUE TITLE
current state of repo does not reproduce on makerchip

### ISSUE THREAD

**Issue by Ravenwater** [stevehoover/warp-v#46]
Quick start link does not yield a working makerchip page:

# Quick Links

### Explore WARP-V

WARP-V is easiest to explore in Makerchip. You can:
  - <a href="http://www.makerchip.com/sandbox?code_url=https:%2F%2Fraw.githubusercontent.com%2Fstevehoover%2Fwarp-v%2Fmaster%2Fwarp-v.tlv" target="_blank" atom_fix="_">open the entire WARP-V model as a single file</a>

The diagram tab will error out.

**Comment by stevehoover** [comment]
Yes, that's true, the diagram tool will sometimes fail on large designs. It's an open-source tool (graph-viz) that I don't really care to dig into. Other forms of visualization are coming.
